name: Trigger API

on:
  workflow_dispatch:
  schedule:
    - cron: "12 * * * *"
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Content
        run: |
          if [ $(($RANDOM % 5)) == 0 ]; then curl -L 'https://onedrive-vercel-index-blush-iota.vercel.app/api/raw/?path=/README.md'; fi
