name: Trigger API

on:
  schedule:
    - cron: "12 * * * *"
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Content
        run: |
          curl -L 'https://onedrive-vercel-index-blush-iota.vercel.app/api/raw/?path=/README.md'
